//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.RecoverAnswer = new HashSet<RecoverAnswer>();
        }
    
        public long answerId { get; set; }
        public string answerContent { get; set; }
        public System.DateTime answerTime { get; set; }
        public long questionId { get; set; }
        public long userId { get; set; }
        public string answerPublishedTime { get; set; }
    
        public virtual ICollection<RecoverAnswer> RecoverAnswer { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
