//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleComment = new HashSet<ArticleComment>();
        }
    
        public long articleId { get; set; }
        public string articleTitle { get; set; }
        public string articleContent { get; set; }
        public System.DateTime articleTime { get; set; }
        public long userId { get; set; }
        public Nullable<int> articleViewNum { get; set; }
        public Nullable<int> articleCommentNum { get; set; }
        public Nullable<int> articlePraiseNum { get; set; }
        public Nullable<int> articleShareNum { get; set; }
    
        public virtual ICollection<ArticleComment> ArticleComment { get; set; }
        public virtual User User { get; set; }
    }
}
