//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.School = new HashSet<School>();
        }
    
        public int cityId { get; set; }
        public string cityName { get; set; }
        public int provinceId { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<School> School { get; set; }
    }
}
