//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int messageId { get; set; }
        public string messageContent { get; set; }
        public long messageSendUserId { get; set; }
        public System.DateTime messageTime { get; set; }
        public bool messageIfRead { get; set; }
        public long messageReceiveUserId { get; set; }
        public int lastChatId { get; set; }
        public string messageWhoSend { get; set; }
    
        public virtual LastChat LastChat { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
