//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanComeOn
    {
        public long planComeOnId { get; set; }
        public string planComeOnWrite { get; set; }
        public Nullable<long> planId { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<System.DateTime> planComeOnTime { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual User User { get; set; }
    }
}
