//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Plancomment = new HashSet<Plancomment>();
            this.Supervice = new HashSet<Supervice>();
            this.PlanComeOn = new HashSet<PlanComeOn>();
            this.Clocklog = new HashSet<Clocklog>();
        }
    
        public long planId { get; set; }
        public string planTitle { get; set; }
        public string planContent { get; set; }
        public System.DateTime planTime { get; set; }
        public Nullable<int> planViewNum { get; set; }
        public long userId { get; set; }
        public string planPublishedTime { get; set; }
        public Nullable<int> planCommentNum { get; set; }
        public Nullable<int> planComeOnNum { get; set; }
        public Nullable<int> planSuperviseNum { get; set; }
        public Nullable<System.DateTime> planStartTime { get; set; }
        public Nullable<System.DateTime> planEndTime { get; set; }
        public Nullable<bool> planIsFinish { get; set; }
    
        public virtual ICollection<Plancomment> Plancomment { get; set; }
        public virtual ICollection<Supervice> Supervice { get; set; }
        public virtual ICollection<PlanComeOn> PlanComeOn { get; set; }
        public virtual ICollection<Clocklog> Clocklog { get; set; }
        public virtual User User { get; set; }
    }
}
