//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public long questionId { get; set; }
        public string questionContent { get; set; }
        public System.DateTime questionTime { get; set; }
        public Nullable<int> questionViewNum { get; set; }
        public long userId { get; set; }
        public string questionTitle { get; set; }
        public Nullable<int> questionReplyNum { get; set; }
        public string questionNewestReply { get; set; }
        public string questionPublishedTime { get; set; }
        public Nullable<long> newReplyUserId { get; set; }
        public string newReplyUserName { get; set; }
        public string newReplyUserImg { get; set; }
        public Nullable<int> qCategoryId { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual QCategory QCategory { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual Question Question2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
