//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperiorLetter
    {
        public long superiorLetterId { get; set; }
        public long superiorLetterSendUId { get; set; }
        public long superiorLetterReceiveUId { get; set; }
        public bool superiorLetterIfReply { get; set; }
        public string superiorLetterNewestRly { get; set; }
        public int superiorLetterIfComment { get; set; }
        public bool superiorLetterIfRead { get; set; }
        public Nullable<System.DateTime> superiorLetterNewestRlyTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
